### PR TITLE
Fix #158: Add retry logic to HeartbeatService

### LINKED ISSUE #158: HeartbeatService not starting if master BookKeeper not up
If the BookKeeperServer on the master node in a cluster is not running, the HeartbeatService on a worker node will not be able to connect to it and fail to start.

### PR DESCRIPTION
**Pull request by jordanw-bq**
- Successfully tested on a Qubole cluster

### CODE REVIEW

**Comment by vrajat** [comment]
The approach seems reasonable. @abhishekdas99 how does Hadoop solve this ? Similar approach ?

File: rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java [hunk 1]
```diff
@@ -54,13 +54,33 @@ public void handleHeartbeat(String workerHostname)
    */
   private void startHeartbeatService(Configuration conf)
   {
-    try {
-      this.heartbeatService = new HeartbeatService(conf);
-      heartbeatService.startAsync();
-    }
-    catch (TTransportException e) {
-      log.fatal("Could not start heartbeat service", e);
+    final int retryInterval = CacheConfig.getServiceRetryInterval(conf);
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: The main problem here is we are creating the bookkeeper client in the constructor of HeartbeatService. So in case when there is an exception while creating the bookkeeper client, we are catching the exception in `startHeartbeatService`

What we should do is to move the creation of bookkeeper client in the `runOneIteration` method and create the client only once. In that case `runOneIteration` takes care of the retry part. So even if the client doesn't get created at first attempt, it will retry at regular interval defined by `heartbeatInterval`

Comment (jordanw-bq) [reply rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: Makes sense. I've moved the creation of the client to `runOneIteration`, and the change is working on QiB.

File: rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java [hunk 2]
```diff
@@ -108,15 +101,22 @@ protected void startUp()
...
-    protected void runOneIteration() throws TException
+    protected void runOneIteration()
     {
       try {
+        if (bookkeeperClient == null) {
+          this.bookkeeperClient = new BookKeeperFactory().createBookKeeperClient(masterHostname, conf);
+          log.debug(String.format("Connected to master node [%s]", masterHostname));
+        }
         log.debug(String.format("Sending heartbeat to %s", masterHostname));
         bookkeeperClient.handleHeartbeat(InetAddress.getLocalHost().getCanonicalHostName());
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: There will be a NPE here if `bookkeeperClient` is null

Comment (abhishekdas99) [reply rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: My bad.. You are right. `bookkeeperClient` won't be null here

**Comment by vrajat** [comment]
I understand why you moved the client setup to `runOneIteration`. You are using `runOneIteration` as a defacto retry mechanism. One problem with this approach is that the rubix worker is active even though heartBeatService is not yet up. We should try to avoid this situation. Ideally (some of this specific to QDS), Rubix and the machine should be marked as up if all services are up. Rubix and machine should be marked unhealthy if all services are not up. This includes the heartBeatService. Right now, it again goes back to best effort. 

So I suggest the following change: Move initialization of the client back to constructor using a function.
    
    this.bookKeeperClient = initializeClientWithRetry(...)

Implement the retry login in `initializeClientWithRetry`. This will also help to unit test it. You can mock `new BookKeeperFactory().createBookKeeperClient(masterHostname, conf);` to return errors to unit test the retry logic as well. The fact that it is easier to unit test is a good sign that this is a better design.

File: rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java [hunk 3]
```diff
@@ -91,13 +86,50 @@ private void startHeartbeatService(Configuration conf)
...
+        }
+
+        try {
+          Thread.sleep(retryInterval);
+        }
+        catch (InterruptedException e) {
+          Thread.currentThread().interrupt();
+        }
+      }
+
```
Comment (vrajat) [inline rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: Log a fatal message here.

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+        new RetryingBookkeeperClient(
+            new TSocket("localhost", CacheConfig.getServerPort(conf), CacheConfig.getClientTimeout(conf)),
+            CacheConfig.getMaxRetries(conf)));
+
+    startBookKeeperServer();
+    final WorkerBookKeeper.HeartbeatService heartbeatService = new WorkerBookKeeper.HeartbeatService(conf, bookKeeperFactory);
+  }
+
+  /**
+   * Verify that the heartbeat service no longer attempts to connect once it runs out of retry attempts.
```
Comment (vrajat) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java]: I am not sure if its possible with mock in Java. Can you test if connection is established after a few failures ? Skip if its too hard.

File: rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java [hunk 5]
```diff
@@ -91,13 +86,50 @@ private void startHeartbeatService(Configuration conf)
...
+    {
+      final int retryInterval = CacheConfig.getServiceRetryInterval(conf);
+      final int maxRetries = CacheConfig.getServiceMaxRetries(conf);
+
+      for (int failedStarts = 0; failedStarts < maxRetries; ) {
+        try {
+          return bookKeeperFactory.createBookKeeperClient(masterHostname, conf);
+        }
+        catch (TTransportException e) {
+          System.out.println("Could not start client for heartbeat service: ");
```
[the remark this answers is not in the document]
Comment (jordanw-bq) [reply rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: Stdout message was leftover from testing. I've removed this & changed the log level for the log statement.

File: rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java (hunk 3 above)
Comment (jordanw-bq) [reply rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java]: Added a fatal log message.

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java (hunk 4 above)
Comment (jordanw-bq) [reply rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java]: Added unit test for connecting after a few retries (see line 99 `testHeartbeatRetryLogic_connectAfterRetries()`)

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java [hunk 6]
```diff
@@ -0,0 +1,189 @@
...
+    startBookKeeperServer();
+    final WorkerBookKeeper.HeartbeatService heartbeatService = new WorkerBookKeeper.HeartbeatService(conf, bookKeeperFactory);
+  }
+
+  /**
+   * Start an instance of the BookKeeper server.
+   *
+   * @throws InterruptedException if the current thread is interrupted while sleeping.
+   */
+  private void startBookKeeperServer() throws InterruptedException
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java]: Lets invoke this method in BeforeMethod

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java [hunk 7]
```diff
@@ -0,0 +1,189 @@
...
+    };
+    thread.start();
+  }
+
+  /**
+   * Stop the currently running BookKeeper server instance.
+   *
+   * @throws InterruptedException if the current thread is interrupted while sleeping.
+   */
+  private void stopBookKeeperServer() throws InterruptedException
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java]: Invoke this in AfterMethod

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java [hunk 8]
```diff
@@ -0,0 +1,189 @@
...
+  }
+
+  /**
+   * Verify that the heartbeat service correctly makes a connection using a BookKeeper client after a number of retries.
+   */
+  @Test
+  public void testHeartbeatRetryLogic_connectAfterRetries()
+  {
+    final int retryInterval = 500;
+    CacheConfig.setServiceRetryInterval(conf, retryInterval);
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java]: as BeforeMethod has already started the server, lets stop it first and then invoke startBookKeeperServerWithDelay

**Comment by abhishekdas99** [comment]
The CI build is failing. Other than that it looks fine. @jordanw-bq can you take care of the CI build issue

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeper.java [hunk 9]
```diff
@@ -36,12 +39,16 @@
...
+  private static final Log log = LogFactory.getLog(TestBookKeeper.class);
+
   private MetricRegistry metrics;
   private Configuration conf;
 
   @BeforeMethod
-  public void setUp() throws Exception
+  public void setUp(Method method) throws Exception
   {
+    log.info("Starting test " + method.getName());
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeper.java]: Remove this

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperMetrics.java [hunk 10]
```diff
@@ -52,6 +58,12 @@ public void setUp() throws IOException
     bookKeeper = new CoordinatorBookKeeper(conf, metrics);
   }
 
+  @BeforeMethod
+  public void setUpForTest(Method method)
+  {
+    log.info("Starting test " + method.getName());
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperMetrics.java]: Same here

File: rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperServer.java [hunk 11]
```diff
@@ -62,8 +63,10 @@ public void initializeCacheDirectories() throws IOException
   }
 
   @BeforeMethod
-  public void setUp()
+  public void setUp(Method method)
   {
+    log.info("Starting test " + method.getName());
```
Comment (abhishekdas99) [inline rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperServer.java]: Same here

**Comment by abhishekdas99** [comment]
@jordanw-bq Do we need `log.info("Starting test " + method.getName());` . If not can we remove this log

**Comment by jordanw-bq** [comment]
@abhishekdas99 I added those lines to help determine the cause of the Travis build timeout, since I didn't experience it when building locally. Now that the build is passing, they can be (and have been) removed.

**Comment by abhishekdas99** [comment]
LGTM
