### PR TITLE
fix: dev: #297: Fix No such file or directory exception in bks logs

### LINKED ISSUE #297: Cache data directories to be made writable for the creation of metadata files

### PR DESCRIPTION
**Pull request by garvit-gupta**
The exception occurred because the bks service did not have write privileges over the cache table directories and consequently was not able to create metadata files in the case of Non local reads. 

- Making the cached table directories writable recursively from Cache util

fixes #297

### CODE REVIEW

File: rubix-spi/src/main/java/com/qubole/rubix/spi/CacheUtil.java [hunk 1]
```diff
@@ -208,7 +208,11 @@ private static void createCacheDirectory(String cacheDirPath)
   {
     final File cacheDir = new File(cacheDirPath);
     cacheDir.mkdirs();
-    cacheDir.setWritable(true, false);
+    File parentFile = cacheDir;
+    do {
+      parentFile.setWritable(true, false);
+      parentFile = parentFile.getParentFile();
+    } while (parentFile.getAbsolutePath().contains("fcache"));
```
Comment (abhishekdas99) [inline rubix-spi/src/main/java/com/qubole/rubix/spi/CacheUtil.java]: Remove "fcache" and get it from the config

Comment (garvit-gupta) [reply rubix-spi/src/main/java/com/qubole/rubix/spi/CacheUtil.java]: Made the change
